#!/usr/bin/env bash
#MISE description="Run comprehensive pre-push checks: format, lint, and test"

set -eux

# Check formatting
cargo fmt --all --check

# Check no lint warning
cargo clippy --locked --all-targets --all-features -- -D warnings

# Run tests
cargo nextest run --locked
