blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/ilaborie/clawspec/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/ilaborie/clawspec/blob/main/README.md
    about: Check the documentation for usage information