name: Feature Request
description: Suggest a new feature or enhancement for clawspec
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees:
  - ilaborie

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I've also considered...

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would benefit you and others.
      placeholder: This feature would help me...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: If possible, provide a code example or mock-up of how you'd like to use this feature.
      render: rust

  - type: dropdown
    id: complexity
    attributes:
      label: Implementation Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - "Low - Minor change or addition"
        - "Medium - Moderate change requiring some design"
        - "High - Major change requiring significant design and implementation"
        - "Unknown - I'm not sure"
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to implementing this feature?
      options:
        - label: "I'm willing to submit a pull request for this feature"
        - label: "I can help with testing once implemented"
        - label: "I can help with documentation"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here.