openapi: 3.1.0
info:
  title: ''
  version: ''
paths:
  /api/observations:
    get:
      operationId: get-observations
      parameters:
      - name: offset
        in: query
        required: false
        schema:
          type: integer
          minimum: 0
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          minimum: 0
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListObservations'
    post:
      operationId: post-observations
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PartialObservation'
            example:
              color: blue
              name: Parrot
              notes: null
              position:
                lat: -25.1
                lng: 12.4
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObservationId'
  /api/observations/{observation_id}:
    put:
      operationId: put-observations-observation-id
      parameters:
      - name: observation_id
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/ObservationId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PartialObservation'
            example:
              color: green
              name: Updated Parrot
              notes: Updated via API
              position:
                lat: -26.2
                lng: 13.5
      responses:
        '200':
          description: ''
    delete:
      operationId: delete-observations-observation-id
      parameters:
      - name: observation_id
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/ObservationId'
      responses:
        '200':
          description: ''
          content:
            application/json: {}
    patch:
      operationId: patch-observations-observation-id
      parameters:
      - name: observation_id
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/ObservationId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchObservation'
            example:
              color: red
              name: Partially Updated Parrot
              notes: null
              position: null
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Observation'
components:
  schemas:
    ListObservations:
      type: object
      required:
      - observations
      properties:
        observations:
          type: array
          items:
            $ref: '#/components/schemas/Observation'
    Observation:
      allOf:
      - $ref: '#/components/schemas/PartialObservation'
      - type: object
        required:
        - id
        properties:
          id:
            $ref: '#/components/schemas/ObservationId'
    ObservationId:
      type: integer
      minimum: 0
