openapi: 3.1.0
info:
  title: ''
  version: ''
paths:
  /api/observations:
    get:
      operationId: get-observations
      parameters:
      - name: offset
        in: query
        required: false
        schema:
          type: string
        style: form
      - name: limit
        in: query
        required: false
        schema:
          type: string
        style: form
      responses: {}
    post:
      operationId: post-observations
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PartialObservation'
            example:
              color: blue
              name: Parrot
              notes: null
              position:
                lat: -25.1
                lng: 12.4
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Observation'
components:
  schemas:
    ListObservations:
      type: object
      required:
      - observations
      properties:
        observations:
          type: array
          items:
            $ref: '#/components/schemas/Observation'
    Observation:
      allOf:
      - $ref: '#/components/schemas/PartialObservation'
      - type: object
        required:
        - id
        properties:
          id:
            $ref: '#/components/schemas/ObservationId'
