#!/usr/bin/env bash
#MISE description="Run all tests using nextest and include doctests"

set -eux

# Tests without features
cargo nextest run --no-fail-fast

# Tests with redaction feature
cargo nextest run --no-fail-fast --features redaction

# Tests in docs
cargo test --doc

# Tests in docs with redaction feature
cargo test --doc --features redaction

