name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: info
  MSRV: "1.88"

jobs:
  check:
    name: ✅ Check Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Rust environment
        uses: ./.github/actions/setup-rust
        with:
          rust-version: stable
          cache-key-suffix: stable
        
      - name: Run comprehensive checks
        run: mise run check

  security:
    name: 🔒 Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Rust environment
        uses: ./.github/actions/setup-rust
        with:
          rust-version: stable
          components: ''
          cache-key-suffix: security
        
      - name: Run security audit
        run: mise run audit
        continue-on-error: true

  msrv:
    name: 🦀 Minimum Supported Rust Version
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Rust environment
        uses: ./.github/actions/setup-rust
        with:
          rust-version: ${{ env.MSRV }}
          cache-key-suffix: msrv
        
      - name: Check compilation with MSRV
        run: cargo check --locked --all-targets --all-features

  minimal-versions:
    name: 📦 Minimal Dependency Versions
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Rust environment (nightly)
        uses: ./.github/actions/setup-rust
        with:
          rust-version: nightly
          components: ''
          cache-key-suffix: nightly
        
      - name: Generate Cargo.lock with minimal versions
        run: cargo +nightly update -Z minimal-versions
        
      - name: Setup Rust toolchain (MSRV)
        uses: ./.github/actions/setup-rust
        with:
          rust-version: ${{ env.MSRV }}
          components: ''
          cache-key-suffix: minimal-msrv
          
      - name: Check compilation with minimal versions
        run: cargo check --locked --all-targets --all-features

  beta:
    name: 🧪 Beta Rust Channel
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Rust environment
        uses: ./.github/actions/setup-rust
        with:
          rust-version: beta
          cache-key-suffix: beta
        
      - name: Run comprehensive checks with beta
        run: mise run check
